name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Update to PHP 8.2
    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress
    - name: Copy .env
      run: cp .env.example .env
    - name: Generate Application Key
      run: php artisan key:generate
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Run Migrations
      run: php artisan migrate --force
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
    - name: Run Tests
      run: php artisan test
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
    
    - name: Notify on Failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const nodemailer = require("nodemailer");

          async function main() {
            let transporter = nodemailer.createTransport({
              service: 'gmail',
              auth: {
                user: process.env.GMAIL_USERNAME,
                pass: process.env.GMAIL_PASSWORD
              }
            });

            let info = await transporter.sendMail({
              from: '"GitHub Actions" <no-reply@example.com>',
              to: "tongsreng@itc.edu.kh",
              subject: "Build Failed",
              text: `The build for commit ${context.sha} has failed. Please review the logs and address the issues.`
            });

            console.log("Message sent: %s", info.messageId);
          }

          main().catch(console.error);

          // Notify the committer
          const { payload } = context;
          const committerEmail = payload.head_commit.committer.email;

          main().then(() => {
            return transporter.sendMail({
              from: '"GitHub Actions" <no-reply@example.com>',
              to: committerEmail,
              subject: "Build Failed",
              text: `The build for your commit ${context.sha} has failed. Please review the logs and address the issues.`
            });
          }).catch(console.error);
      env:
        GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
