name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Update to PHP 8.2
    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress
    - name: Copy .env
      run: cp .env.example .env
    - name: Generate Application Key
      run: php artisan key:generate
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Run Migrations
      run: php artisan migrate --force
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
    - name: Run Tests
      run: php artisan test
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
